xacro:
  WheelBase: 0.137
  ModuleWidth: 0.27
  TrackWidth: 0.052
  ChassisTopAndBottomClearance: 0.013
  WheelMass: 0.1
  ChassisMass: 2.5

  JointDiameter: 0.048
  JointABottomClearance: 0.013
  JointAMass: 0.1
  JointBMass: 0.05
  JointWidth: 0.067 # At the moment ${EquivalentWheelDiameter-2*JointABottomClearance}