# From: https://github.com/ros-drivers/usb_cam/blob/main/src/usb_cam_node.cpp

/**:
    ros__parameters:
      framerate: 30.0
      image_width: 640
      image_height: 480
      pixel_format: "yuyv2rgb"

      # Following parameters should be set on launch:
      # device_id, camera_name, frame_id
