- {
  msg_id: 0x21, # Track velocity command
  modules: "all",
  length: 8,
  is_command: true,
  fields: [
    { name: "left_back_wheel",  type: "command", mode: "velocity", data_type: "float32", offset: 0, scale: 0.104719, bias: 0.0 },
    { name: "right_back_wheel", type: "command", mode: "velocity", offset: 4, scale: 0.104719 } # RPM to rad/s
  ]
}
- {
  msg_id: 0x22, # Track velocity state
  length: 8,
  fields: [
    { name: "left_front_wheel",  mode: "velocity", type: "state", scale: 0.104719 },
    { name: "right_front_wheel", mode: "velocity", offset: 4, scale: 0.104719 },
    { name: "left_back_wheel",   mode: "velocity", scale: 0.104719 },
    { name: "right_back_wheel",  mode: "velocity", offset: 4, scale: 0.104719 },
  ]
}
- {
  msg_id: 0x32, # Yaw joint feedback
  modules: "skip_first",
  length: 4,
  fields: [
    { name: "yaw_joint", scale: 0.017453 }, # degrees to radians
  ]
}
- {
  msg_id: 0x51, # Arm base commands (P + R)
  modules: "only_first",
  length: 8,
  is_command: true,
  fields: [
    { name: "base_pitch_arm_joint", type: "command" },
    { name: "base_roll_arm_joint",  type: "command", offset: 4 },
  ]
}
- {
  msg_id: 0x52, # Arm base states (P + R)
  modules: "only_first",
  length: 8,
  fields: [
    { name: "base_pitch_arm_joint", },
    { name: "base_roll_arm_joint",  offset: 4 },
  ]
}
- {
  msg_id: 0x53, # Arm elbow commands (P)
  modules: "only_first",
  length: 4,
  is_command: true,
  fields: [
    { name: "elbow_pitch_arm_joint", type: "command" },
  ]
}
- {
  msg_id: 0x54, # Arm elbow states (P)
  modules: "only_first",
  length: 4,
  fields: [
    { name: "elbow_pitch_arm_joint", },
  ]
}
- {
  msg_id: 0x55, # Arm forearm commands (R)
  modules: "only_first",
  length: 4,
  is_command: true,
  fields: [
    { name: "forearm_roll_arm_joint", type: "command" },
  ]
}
- {
  msg_id: 0x56, # Arm forearm states (R)
  modules: "only_first",
  length: 4,
  fields: [
    { name: "forearm_roll_arm_joint", },
  ]
}
- {
  msg_id: 0x57, # Arm wrist pitch command
  modules: "only_first",
  length: 4,
  is_command: true,
  fields: [
    { name: "wrist_pitch_arm_joint", type: "command" },
  ]
}
- {
  msg_id: 0x58, # Arm wrist pitch state
  modules: "only_first",
  length: 4,
  fields: [
    { name: "wrist_pitch_arm_joint", },
  ]
}
- {
  msg_id: 0x59, # Arm wrist roll command
  modules: "only_first",
  length: 4,
  is_command: true,
  fields: [
    { name: "wrist_roll_arm_joint", type: "command" },
  ]
}
- {
  msg_id: 0x5A, # Arm wrist roll state
  modules: "only_first",
  length: 4,
  fields: [
    { name: "wrist_roll_arm_joint", },
  ]
}